language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - "pip install flake8 --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py develop"
before_script: flake8 crtauth/ test/
script: python setup.py test
